version: '3.8'

services:
  blog-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend-s148
    ports:
      - '8080:3000'
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"